server:
  servlet:
    context-path: /fiap-spring
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fiap
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

    # Spring Mail Properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: password

  # Other properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  jpa:
    show-sql: true

