server:
  servlet:
    context-path: /fiap-spring
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fiap
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
  